# Generated by Django 3.1.7 on 2021-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='StockID',
            field=models.ManyToManyField(blank=True, null=True, to='stocks_api.Stock'),
        ),
    ]
