# Generated by Django 3.1.7 on 2021-04-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0002_auto_20210405_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='StockID',
        ),
        migrations.CreateModel(
            name='WatchlistStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_api.stock')),
                ('WatchlistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_api.watchlists')),
            ],
        ),
    ]
