# Generated by Django 3.1.7 on 2021-04-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0003_auto_20210405_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyStockSerializer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='portfoliostocks',
            name='TransactionID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks_api.transactions'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='PortfolioID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks_api.portfolios'),
        ),
    ]
