# Generated by Django 3.1.7 on 2021-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0004_auto_20210406_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyStockSerializer',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='Unrealizedvalue',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='UnrealizedvalueCurrent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
