# Generated by Django 3.1.7 on 2021-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0005_auto_20210408_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='UnrealizedValueCurrent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
